### ISSUE TITLE
Implement support for containerd as CRI

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener-extension-os-suse-chost#42]
**How to categorize this issue?**

/area os usability
/kind enhancement
/priority 3
/os suse-chost

**What would you like to be added**:
Implement the requirements from https://github.com/gardener/gardener/blob/master/docs/proposals/10-shoot-additional-container-runtimes.md#design-details.

**Why is this needed**:
To enable containerd as CRI for CoreOS/Flatcar. Also needed for the docker deprecation https://github.com/gardener/gardener/issues/4110

**Comment by vpnachev** [comment]
Some findings so far
1. The binaries are installed in `/usr/sbin` and need to be linked from `/usr/bin`.
2. `ctr` is available as `containerd-ctr`, so it also have to be renamed/linked  as `ctr`.
3. `containerd.service` file is missing in the OS, so it cannot be simply started with `systemctl start containerd`
4. `containerd-shim-runc-v[12]` are missing

**Comment by vpnachev** [comment]
Some other findings, `runc` is also missing on the node
- I tried to re-use `docker-runc` by symbolic link
- Alternatively, installed `runc` from https://github.com/opencontainers/runc/releases/download/v1.0.0-rc95/runc.amd64

In both cases the nodes are healthy and pods can be created, but pod termination is failing with
```
error killing pod: [failed to "KillContainer" for "webserver" with KillContainerError: "rpc error: code = Unknown desc = failed to stop container \"f46c66da7b7118b0207cc0b5a93c7f3c119e1f842fe9acf40498c4057327527e\": unknown error after kill: runc did not terminate sucessfully: container_linux.go:419: signaling init process caused: permission denied\n: unknown", failed to "KillPodSandbox" for "9df16fc6-243e-4259-a24e-39d95b5ea71d" with KillPodSandboxError: "rpc error: code = Unknown desc = failed to stop container \"f46c66da7b7118b0207cc0b5a93c7f3c119e1f842fe9acf40498c4057327527e\": failed to kill container \"f46c66da7b7118b0207cc0b5a93c7f3c119e1f842fe9acf40498c4057327527e\": unknown error after kill: runc did not terminate sucessfully: container_linux.go:419: signaling init process caused: permission denied\n: unknown"]
```
Because of this, the conformance tests are failing, so this setup cannot be used in productive clusters.



Here is the shoot spec that I am using to run the validation
```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  name: foo
  namespace: bar
spec:
  addons:
    kubernetesDashboard:
      authenticationMode: basic
      enabled: false
    nginxIngress:
      enabled: false
      externalTrafficPolicy: Cluster
  cloudProfileName: aws
  hibernation:
    enabled: false
  kubernetes:
    allowPrivilegedContainers: false
    kubeAPIServer:
      enableAnonymousAuthentication: false
      enableBasicAuthentication: false
      requests:
        maxMutatingInflight: 200
        maxNonMutatingInflight: 400
    kubeControllerManager:
      nodeCIDRMaskSize: 24
      nodeMonitorGracePeriod: 2m0s
      podEvictionTimeout: 2m0s
    kubeProxy:
      enabled: true
      mode: IPTables
    kubelet:
      failSwapOn: true
      kubeReserved:
        cpu: 80m
        memory: 1Gi
        pid: 20k
    version: 1.20.6
  maintenance:
    autoUpdate:
      kubernetesVersion: false
      machineImageVersion: false
    timeWindow:
      begin: 010000+0000
      end: 020000+0000
  networking:
    nodes: 10.250.0.0/16
    pods: 100.96.0.0/11
    services: 100.64.0.0/13
    type: calico
  provider:
    infrastructureConfig:
      apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
      kind: InfrastructureConfig
      networks:
        vpc:
          cidr: 10.250.0.0/16
        zones:
        - internal: 10.250.112.0/22
          name: eu-west-1a
          public: 10.250.96.0/22
          workers: 10.250.0.0/19
    type: aws
    workers:
    - cri:
        name: containerd
      machine:
        image:
          name: suse-chost
          version: 15.2.20210610 # ami-0cae8a3a77df68846
        type: c5.large
      maxSurge: 1
      maxUnavailable: 0
      maximum: 2
      minimum: 2
      name: containerd
      systemComponents:
        allow: true
      volume:
        size: 50Gi
        type: gp2
      zones:
      - eu-west-1a
  purpose: development
  region: eu-west-1
```

In this branch https://github.com/vpnachev/gardener-extension-os-suse-chost/commits/containerd I am pushing the changes that I am currently using to enable containerd in this extension.
